# Generated by Django 2.1.1 on 2019-07-25 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='t_title',
            field=models.CharField(max_length=1000, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='testpoint',
            name='t_img',
            field=models.ImageField(null=True, upload_to='../../static/img/'),
        ),
        migrations.AlterField(
            model_name='testpoint',
            name='t_remark',
            field=models.CharField(max_length=1000, null=True, verbose_name='影响范围'),
        ),
        migrations.AlterField(
            model_name='testpoint',
            name='t_storage',
            field=models.IntegerField(default='0', null=True, verbose_name='是否入库'),
        ),
        migrations.AlterField(
            model_name='testpoint',
            name='t_usable',
            field=models.IntegerField(default='0', null=True, verbose_name='是否失效'),
        ),
    ]
