# Generated by Django 2.1.1 on 2019-07-25 07:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_auto_20190725_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='t_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
    ]
