# Generated by Django 2.1.1 on 2019-08-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_knowledge_t_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_versions', models.CharField(max_length=1000, verbose_name='版本')),
                ('t_module', models.CharField(max_length=1000, verbose_name='模块')),
                ('t_testpointVal', models.CharField(max_length=1000, verbose_name='测试点')),
                ('t_precondition', models.CharField(max_length=1000, verbose_name='前置条件')),
                ('t_step', models.CharField(max_length=1000, verbose_name='操作步骤')),
                ('t_expectedResult', models.CharField(max_length=1000, verbose_name='预期结果')),
                ('t_actualResults', models.CharField(max_length=1000, verbose_name='实际结果')),
                ('t_pass', models.CharField(max_length=1000, verbose_name='是否通过')),
                ('t_effective', models.CharField(max_length=1000, verbose_name='是否有效')),
                ('t_remark', models.CharField(max_length=100, verbose_name='备注')),
            ],
        ),
    ]
