# Generated by Django 2.1.1 on 2019-08-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_addcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcase',
            name='t_actualResults',
            field=models.CharField(max_length=1000, null=True, verbose_name='实际结果'),
        ),
        migrations.AlterField(
            model_name='addcase',
            name='t_precondition',
            field=models.CharField(max_length=1000, null=True, verbose_name='前置条件'),
        ),
        migrations.AlterField(
            model_name='addcase',
            name='t_remark',
            field=models.CharField(max_length=100, null=True, verbose_name='备注'),
        ),
    ]
