# Generated by Django 2.1.1 on 2019-09-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_auto_20190806_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpoint',
            name='t_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
