# Generated by Django 2.1.1 on 2019-09-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_auto_20190806_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcase',
            name='t_username',
            field=models.CharField(default=1, max_length=30, verbose_name='提交人'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testpoint',
            name='t_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
