# Generated by Django 2.1.1 on 2019-07-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeployIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_ip', models.CharField(max_length=1000, verbose_name='IP')),
                ('t_port', models.CharField(max_length=1000, verbose_name='port')),
                ('t_remark', models.CharField(max_length=1000, null=True, verbose_name='备注')),
            ],
        ),
    ]
