# Generated by Django 2.1.1 on 2019-07-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployip',
            name='t_path',
            field=models.CharField(default='', max_length=1000, verbose_name='路径'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deployip',
            name='t_pswd',
            field=models.CharField(default='', max_length=1000, verbose_name='密码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deployip',
            name='t_user',
            field=models.CharField(default='', max_length=1000, verbose_name='账户'),
            preserve_default=False,
        ),
    ]
