# Generated by Django 2.1.1 on 2019-10-16 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addcard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogInfo',
        ),
    ]
