# Generated by Django 2.1.1 on 2019-08-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddVersions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_versions', models.CharField(max_length=1000, verbose_name='版本游戏名称')),
                ('c_link', models.CharField(max_length=1000, verbose_name='版本游戏链接')),
                ('c_remark', models.CharField(max_length=1000, verbose_name='版本后台说明')),
            ],
        ),
    ]
