# Generated by Django 2.1.1 on 2019-03-04 06:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasesProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='提交日期')),
                ('c_user', models.CharField(max_length=30, null=True, verbose_name='提交人')),
                ('c_project', models.CharField(max_length=100, null=True, verbose_name='用例所属项目')),
                ('c_purpose', models.CharField(max_length=200, null=True, verbose_name='测试目的')),
                ('c_play', models.CharField(max_length=100, null=True, verbose_name='对应玩法')),
                ('c_option', models.CharField(max_length=1000, null=True, verbose_name='创房选项')),
                ('c_operate', models.TextField(null=True, verbose_name='操作步骤')),
                ('c_is_local', models.IntegerField(null=True, verbose_name='是否在本地已生成文件')),
                ('c_remake', models.CharField(max_length=200, null=True, verbose_name='备注')),
                ('c_name', models.CharField(max_length=1000, null=True, verbose_name='用例生成文件名字')),
                ('c_report_id', models.IntegerField(verbose_name='报告id')),
            ],
            options={
                'verbose_name': 'CasesProfile',
                'db_table': 't_cases',
            },
        ),
        migrations.CreateModel(
            name='ReportProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_end_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='用例运行结束时间')),
                ('r_save_dir', models.IntegerField(verbose_name='用例存放路径')),
                ('r_name', models.CharField(max_length=200, null=True, verbose_name='报告名字')),
                ('c_case_id', models.ForeignKey(on_delete=True, to='cases.CasesProfile')),
            ],
            options={
                'verbose_name': 'ReportProfile',
                'db_table': 't_report',
            },
        ),
    ]
