# Generated by Django 2.1.1 on 2019-03-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casesprofile',
            name='c_report_id',
        ),
        migrations.AlterField(
            model_name='reportprofile',
            name='r_save_dir',
            field=models.CharField(max_length=250, verbose_name='用例存放路径'),
        ),
    ]
