# Generated by Django 2.1.1 on 2019-03-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20190304_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesprofile',
            name='c_cards',
            field=models.CharField(default='', max_length=500, null=True, verbose_name='牌型数据'),
        ),
        migrations.AlterField(
            model_name='casesprofile',
            name='c_name',
            field=models.CharField(default='', max_length=1000, verbose_name='用例生成文件名字'),
        ),
        migrations.AlterField(
            model_name='casesprofile',
            name='c_operate',
            field=models.TextField(default='', verbose_name='操作步骤'),
        ),
        migrations.AlterField(
            model_name='casesprofile',
            name='c_option',
            field=models.CharField(default='', max_length=1000, verbose_name='创房选项'),
        ),
        migrations.AlterField(
            model_name='casesprofile',
            name='c_play',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='对应玩法'),
        ),
        migrations.AlterField(
            model_name='casesprofile',
            name='c_project',
            field=models.CharField(default='', max_length=100, verbose_name='用例所属项目'),
        ),
        migrations.AlterField(
            model_name='casesprofile',
            name='c_purpose',
            field=models.CharField(default='', max_length=200, verbose_name='测试目的'),
        ),
        migrations.AlterField(
            model_name='casesprofile',
            name='c_user',
            field=models.CharField(default='', max_length=30, verbose_name='提交人'),
        ),
    ]
