# Generated by Django 2.1.1 on 2019-04-26 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20190320_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesprofile',
            name='c_status',
            field=models.IntegerField(default=0, verbose_name='用例运行状态'),
        ),
    ]
