# Generated by Django 2.1.1 on 2019-07-24 08:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_casesprofile_c_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casesprofile',
            name='c_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 24, 8, 18, 33, 849150, tzinfo=utc), verbose_name='提交日期'),
        ),
    ]
