# Generated by Django 2.1.1 on 2019-07-24 09:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_auto_20190724_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casesprofile',
            name='c_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='提交日期'),
        ),
    ]
