# Generated by Django 2.1.1 on 2019-10-12 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_auto_20190724_0940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportprofile',
            options={'ordering': ('-r_end_time',), 'verbose_name': 'ReportProfile'},
        ),
    ]
