# Generated by Django 2.1.1 on 2019-03-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugprofile',
            name='b_img',
            field=models.ImageField(null=True, upload_to='static/images'),
        ),
    ]
