# Generated by Django 2.1.1 on 2019-07-24 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_bugprofile_b_img'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bugprofile',
            table='t_bug',
        ),
    ]
